---
ansible_port: 22
ansible_user: provisioner
ansible_python_interpreter: /usr/bin/python3
ansible_ssh_private_key_file: # <path to private rsa key>
ansible_become_pass: # <ssh password>
ansible_ssh_pass: # <ssh password>
