---
nginx_user: 'provisioner'
nginx_letsencrypt_root: '/usr/share/nginx/challenges'
nginx_site_root: '/var/www/html/provisioner/'
nginx_events_worker_connections: 512
# Enables or disables emitting nginx version on error pages and in the “Server” response header field.
nginx_http_server_tokens: 'off'
nginx_http_add_headers:
  - 'X-Frame-Options SAMEORIGIN'
  - 'X-Content-Type-Options nosniff'
  - 'X-XSS-Protection "1; mode=block"'
nginx_http_access_log_format: |
  '$remote_addr $remote_user $request_time $upstream_response_time $msec [$time_local] '
  '"$request" $status $body_bytes_sent '
  '"$http_referer" "$http_user_agent"'
nginx_http_server_names_hash_bucket_size: 64
nginx_http_server_names_hash_max_size: 512
nginx_http_sendfile: 'on'
nginx_http_tcp_nopush: 'on'
nginx_http_keepalive_timeout: 60
nginx_http_gzip: 'on'
nginx_http_gzip_types: 'text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml image/svg'
nginx_http_gzip_disable: 'msie6'